name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 #setup nodejs in our runner
      - name: Run a one-line script
        run: 'echo Hello, world!'
      - name: Connect Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: '${{ secrets.TAILSCALE_AUTHKEY }}'

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.SERVER }}'
          username: 'corinty'
          password: '${{ secrets.PASSWORD }}'
          script: |
            # git update to latest codebase on main branch
            cd development
            # Restart
            ./deploy-coffee-ledger
            
